<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230306140202 extends AbstractMigration
{

    protected array $languages = [
        ['en', 'English'],
        ['es', 'Spanish'],
        ['fr', 'French'],
        ['de', 'German'],
        ['it', 'Italian'],
        ['pl', 'Polish'],
        ['uk', 'Ukrainian'],
        ['ru', 'Russian'],
    ];

    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(4) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        foreach ($this->languages as $source) {
            foreach ($this->languages as $target) {
                if ($source !== $target) {
                    $this->addSql(
                        'CREATE TABLE translation_' . strtolower($source[1]) . '_to_' . strtolower($target[1]) . ' (
                                id INT AUTO_INCREMENT NOT NULL, 
                                original VARCHAR(255) NOT NULL, 
                                translation TEXT DEFAULT NULL, 
                                counter INT DEFAULT 0 NOT NULL,
                                PRIMARY KEY(id)
                            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB'
                    );
                }
            }
        }
    }

    public function postUp(Schema $schema): void
    {
        parent::postUp($schema); // TODO: Change the autogenerated stub

        foreach ($this->languages as $language) {
            $this->connection->executeQuery('INSERT INTO language (code, name) VALUES (?, ?)', $language);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE language');

        foreach ($this->languages as $source) {
            foreach ($this->languages as $target) {
                if ($source !== $target) {
                    $this->addSql(
                        'DROP TABLE translation_from_' . $source[1] . '_to_' . $target[1]);
                }
            }
        }
    }
}
